### ISSUE TITLE
(日常維修用)

### ISSUE THREAD

**Issue by SammyLin** [17media/announcement#3]
```yaml  
needMaintenance: true
startAt: 2017-12-22 17:15:00 (GMT+0800)
endAt: 2017-12-22 17:45:00 (GMT+0800)
announcements:
    EN:
        title: "System maintenance"
        description: "Dear users, to ensure the highest stability and performance levels for our services, we’re applying a system update on servers during 17:15 - 17:45 (GMT+8). We apologize for your inconvenience. Should there be any question, please contact our 24/7 customer service. Thank you."
        pic: "17baobao.jpg"
    TW:
        title: "系統維修公告"
        description: "親愛的17用戶，非常感謝您的支持與愛護，為提供您更優質的服務，我們將於 17:15 - 17:45 (GMT+8) 進行系統維護，若造成不便敬請見諒。如有任何問題，歡迎透過客服詢問，我們將盡快為您服務，謝謝！"
        pic: "17baobao.jpg"
    JP:
        title: "システムメンテナンス中"
        description: "日頃より17ライブをご利用いただき、誠にありがとうございます。18：15〜18：45（GMT+9）までの間、緊急システムメンテナンスのため、17ライブのサービスを停止しておりました。ご利用のお客様には多大なご迷惑をおかけしましたことを深くお詫び申し上げます。今後とも17ライブをご愛顧賜りますよう、何卒よろしくお願い申し上げます。メンテナンスに伴う不具合や本件に関するお問い合わせにつきましては、下記へご連絡ください。 お問い合わせ：support@17.media"
        pic: "17baobao.jpg"
    CN:
        title: "系统维修公告"
        description: "亲爱的17用户，非常感谢您的支持与爱护，为提供您更优质的服务，我们将于 17:15 - 17:45 (GMT+8) 进行系统维护，若造成不便敬请见谅。如有任何问题，欢迎透过客服询问，我们将尽快为您服务，谢谢！"
        pic: "17baobao.jpg"
    ID:
        title: "Sistem maintenance"
        description: "Dear user, Untuk meningkatkan performa dan stabilas aplikasi ini, kami melakukan sistem update server pukul 16:15 - 16:45 (GMT +7). Kami mohon maaf atas ketidak nyamannya. Jika ada pertanyaan silakan kontak customer service. Terima kasih."
        pic: "17baobao.jpg"
```
