### ISSUE TITLE
Wave (日常維修用)

### ISSUE THREAD

**Issue by harry-tsai** [17media/announcement#72]
```
needMaintenance: true
sendPubnub: true
startAt: 2017-12-22 17:15:00 (GMT+0800)
endAt: 2017-12-22 17:45:00 (GMT+0800)
announcements:
    EN:
        title: "System Maintenance Announcement"
        description: "WAVE is on 2017/12/22 17:15:00〜17:45:00 (UTC+8) service suspension for routine maintenance.\n\nThe service will be restarted after the maintenance is completed. We apologize for your inconvenience.\n\nIf there is any question please contact our customer service. \n\nWAVE Operation Team.\n\n＊After the maintenance is finished, close and reopen the App to use it normally."
    TW:
        title: "系統維護公告"
        description: "WAVE 於 2017/12/22 17:15:00〜17:45:00 (UTC+8) 暫停服務進行例行維護。\n\n服務將於系統維修完成後重新開啟，造成您的不便還請見諒。\n\n如有任何問題可以寫信至客服信箱。感謝您的支持與諒解，謝謝！ \n\nWAVE 營運團隊敬上。\n\n＊維護結束後，完整關閉 App 並重新開啟即可正常使用。"
    JP:
        title: "システムメンテナンス告知"
        description: "WAVEは定期メンテナンスのため、2017/12/22 18:15:00〜18:45:00 (UTC+9) にてサービスを停止しております。\n\nサービスはメンテナンス終了後に再開させていただきます。ご迷惑をおかけしますが、ご了承お願いいたします。\n\nご質問などございましたら、WAVEカスタマサービスへお問い合わせください。\n\nWAVE運営チーム\n\n＊メンテナンス終了後はアプリを一旦終了し、再度開くと正常にご利用いただけます。"
```
