### ISSUE TITLE
Wave (緊急維修公告用)

### ISSUE THREAD

**Issue by harry-tsai** [17media/announcement#73]
```yaml
needMaintenance: true
sendPubnub: true
startAt: 2017-12-22 17:15:00 (GMT+0800)
endAt: 2017-12-22 17:45:00 (GMT+0800)
announcements:
    EN:
        title: "System Emergency Maintenance Announcement"
        description: "Due to (fill in reason), there is a problem with the system. The engineering team is arranging for an engineer to repair the system at 2017/12/22 17:15:00〜17:45:00 (UTC+8).\n\nThe service will be restarted after the maintenance is completed. We apologize for your inconvenience.\n\nIf there is any question please contact our customer service. \n\nWAVE Operation Team.\n\n＊After the maintenance is finished, close and reopen the App to use it normally."
    TW:
        title: "系統緊急維修公告"
        description: "由於（填寫原因），導致系統發生問題。工程團隊正在安排工程師於 2017/12/22 17:15:00〜17:45:00 (UTC+8) 進行維修。\n\n服務將於系統維修完成後重新開啟，造成您的不便還請見諒。\n\n如有任何問題可以寫信至客服信箱。感謝您的支持與諒解，謝謝！ \n\nWAVE 營運團隊敬上。\n\n＊維護結束後，完整關閉 App 並重新開啟即可正常使用。"
    JP:
        title: "システム緊急メンテナンスのご案内"
        description: "（原因）により、システムに問題が発生しています。 2017/12/22 18:15:00〜18:45:00 (UTC+9) にメンテナンスを実施いたします。\n\nサービスはメンテナンス終了後に再開させていただきます。ご迷惑をおかけしますが、ご了承お願いいたします。\n\nご質問などございましたら、WAVEカスタマサービスへお問い合わせください。\n\nWAVE運営チーム\n\n＊メンテナンス終了後はアプリを一旦終了し、再度開くと正常にご利用いただけます。"
```
